# Generated by Django 5.1.6 on 2025-03-07 07:13

import base.choices
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_delete_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default=base.choices.Status["PENDING"],
                        help_text="Processing status of the image.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "processing_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken to process the image in seconds.",
                        null=True,
                        verbose_name="Processing Time (seconds)",
                    ),
                ),
                (
                    "image_size_before",
                    models.IntegerField(
                        help_text="Size of the image before compression in kilobytes.",
                        verbose_name="Image Size Before (KB)",
                    ),
                ),
                (
                    "image_size_after",
                    models.IntegerField(
                        help_text="Size of the image after compression in kilobytes.",
                        verbose_name="Image Size After (KB)",
                    ),
                ),
                (
                    "image_quality",
                    models.IntegerField(
                        help_text="Quality percentage of the compressed image.",
                        verbose_name="Image Quality (%)",
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        help_text="Upload the original uncompressed image.",
                        upload_to="original_images/",
                        verbose_name="Original Image",
                    ),
                ),
                (
                    "compressed_image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload the compressed version of the image.",
                        null=True,
                        upload_to="compressed_images/",
                        verbose_name="Compressed Image",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Select the product this image belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
