# Generated by Django 5.1.6 on 2025-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_quality",
            field=models.IntegerField(
                blank=True,
                help_text="Quality percentage of the compressed image.",
                null=True,
                verbose_name="Image Quality (%)",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_size_after",
            field=models.IntegerField(
                blank=True,
                help_text="Size of the image after compression in kilobytes.",
                null=True,
                verbose_name="Image Size After (KB)",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_size_before",
            field=models.IntegerField(
                blank=True,
                help_text="Size of the image before compression in kilobytes.",
                null=True,
                verbose_name="Image Size Before (KB)",
            ),
        ),
    ]
