# Generated by Django 5.1.6 on 2025-03-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_image_image_quality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="csv_file",
            field=models.FileField(
                blank=True,
                help_text="product csv file",
                null=True,
                upload_to="csv_file/",
                verbose_name="csv file.",
            ),
        ),
    ]
