# Generated by Django 5.1.6 on 2025-03-09 07:18

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_product_csv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="req_id",
            field=models.CharField(
                default=base.utils.generate_short_uuid,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="csv_file",
            field=models.FileField(
                blank=True,
                help_text="product csv file",
                null=True,
                upload_to="csv_file/",
                verbose_name="CSV file",
            ),
        ),
    ]
