# Generated by Django 5.1.6 on 2025-03-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_req_id_alter_product_csv_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="req_id",
        ),
    ]
