# Generated by Django 5.1.6 on 2025-03-09 07:26

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_remove_product_req_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="req_id",
            field=models.CharField(
                blank=True,
                default=base.utils.generate_short_uuid,
                editable=False,
                max_length=12,
            ),
        ),
    ]
