# Generated by Django 5.1.6 on 2025-03-09 07:27

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_req_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="req_id",
            field=models.CharField(
                default=base.utils.generate_short_uuid,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
