# Generated by Django 5.1.6 on 2025-03-10 06:45

import base.choices
import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_req_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default=base.choices.Status["PENDING"],
                help_text="Processing status of the image.",
                max_length=100,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="req_id",
            field=models.CharField(
                default=base.utils.generate_short_uuid,
                editable=False,
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default=base.choices.Status["PENDING"],
                help_text="Current status of the product img Processing.",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
