# Generated by Django 5.1.6 on 2025-03-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_image_status_alter_product_req_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sr_no",
            field=models.IntegerField(
                blank=True,
                help_text="Unique serial number of the product.",
                null=True,
                verbose_name="Serial Number",
            ),
        ),
    ]
