# Generated by Django 5.1.6 on 2025-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_alter_product_sr_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Processing status of the image.",
                max_length=100,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Current status of the product img Processing.",
                max_length=100,
                verbose_name="Status",
            ),
        ),
    ]
